service: usuarios-crud-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-tscpaths

functions:
  api:
    handler: ./src/index.handler
    events:
      - httpApi:
          path: /
          method: get
